name: "WhereIsIt"
version: "0.4.23"
slug: "whereisit"
description: "Physical storage management for Home Assistant"
url: "https://github.com/D3L05/whereisit"
image: "ghcr.io/d3l05/whereisit-{arch}"
startup: application
arch:
  - aarch64
  - amd64
init: false
map:
  - config:rw
options: {}
schema: {}
ingress: true
ingress_port: 8000
ingress_entry: /
panel_icon: mdi:package-variant-closed

